#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

export ZSHCONFIG="${ZDOTDIR:-$HOME}/.zsh-config"

#-----------------------------------------------------
# for profiling zsh
# https://unix.stackexchange.com/a/329719/27109
#
# zmodload zsh/zprof

#-----------------------------------------------------
# local system binaries
#
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:${PATH}"

#-----------------------------------------------------
# ensure to only execute on ZSH
# https://stackoverflow.com/a/9911082/339302
#
[[ -n "${ZSH_VERSION}" ]] || return

# Load the plugins before scripts
#
source "${ZSHCONFIG}/antibody/zsh-managed-plugins.zsh"

#-----------------------------------------------------
# Load all scripts ${ZSHCONFIG}/lib/*.zsh
#
my_zsh_lib="${ZSHCONFIG}/lib"
if [[ -d "${my_zsh_lib}" ]]; then
	for file in "${my_zsh_lib}"/*.zsh; do
		source "${file}"
	done
fi
unset my_zsh_lib

#-----------------------------------------------------
# https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-1930109
#
# check zsh completion system cache max once per day
#
autoload -Uz compinit 
local seconds_in_day="86400"
if (( $(( $(date +%s) - $(date -r ${HOME}/.zcompdump +%s) )) > ${seconds_in_day} )); then
    compinit 
    touch "${HOME}/.zcompdump"
else
    compinit -C
fi
unset seconds_in_day

#-----------------------------------------------------
# Setting autoloaded functions
#
#my_zsh_fpath="${ZSHCONFIG}/autoloaded"
#fpath=("${my_zsh_fpath}" "${fpath[@]}")
#if [[ -d "${my_zsh_fpath}" ]]; then
#	for func in "${my_zsh_fpath}"/*; do
#		autoload -Uz "${func:t}"
#	done
#fi
#unset my_zsh_fpath
